# Generated by Django 4.2.24 on 2025-09-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administrative_posts',
                'ordering': ['municipality__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Suco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('administrative_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucos', to='core.administrativepost')),
            ],
            options={
                'db_table': 'sucos',
                'ordering': ['administrative_post__name', 'name'],
                'unique_together': {('administrative_post', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Aldeia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('suco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldeias', to='core.suco')),
            ],
            options={
                'db_table': 'aldeias',
                'ordering': ['suco__name', 'name'],
                'unique_together': {('suco', 'name')},
            },
        ),
        migrations.AddField(
            model_name='administrativepost',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_posts', to='core.municipality'),
        ),
        migrations.AddField(
            model_name='user',
            name='administrative_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.administrativepost'),
        ),
        migrations.AddField(
            model_name='user',
            name='aldeia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.aldeia'),
        ),
        migrations.AddField(
            model_name='user',
            name='suco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.suco'),
        ),
        migrations.AlterField(
            model_name='user',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.municipality'),
        ),
        migrations.AlterUniqueTogether(
            name='administrativepost',
            unique_together={('municipality', 'name')},
        ),
    ]
