# Generated by Django 4.2.24 on 2025-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_administrativepost_municipality_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['user_id'], name='children_user_id_461969_idx'),
        ),
    ]
