# Generated by Django 4.2.24 on 2025-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_child_user_id_child_children_user_id_461969_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
