# Generated by Django 4.2.24 on 2025-09-22 02:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_child_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='defaults/user.png', null=True, upload_to=core.models.user_image_upload_path),
        ),
    ]
